Update SDK, Product, Segmentation, Disbursement, Webhook integration
AltScore/altscore-python pull request #32
Opened 2024-10-25 03:30 UTC by rrodriguez-consulting

2024-10-25 20:04 UTC, IlicicAxel commented
LGTM!

2024-10-25 20:04 UTC, IlicicAxel approved these changes

2024-10-29 22:09 UTC, paulor3nato requested changes

2024-10-29 22:09 UTC, paulor3nato commented on src/altscore/cms/model/dpa_products.py
> +class UpdateDPAProductAPIDTO(BaseModel):
Probablemente yo lo puse así. Pero si el update no se puede hacer solo para el campo que se envía porqué el back no lo maneja entonces deberíamos restringir aquí tambien haciendo que el modelo igual al de create.

2024-10-30 20:02 UTC, merged