added basic logic of borrower fields values migration
AltScore/altscore-python pull request #33
Opened 2024-11-04 20:18 UTC by pgallardor

2024-11-06 15:26 UTC, IlicicAxel commented on requirements.txt
Habría que agregar los reqs en el setup.py

2024-11-06 15:30 UTC, IlicicAxel commented on requirements.txt
Y bumpear la version

2024-11-14 13:17 UTC, paulor3nato requested changes

2024-11-14 13:17 UTC, paulor3nato commented on setup.py
> +        "pyjwt",
ponles version

2024-11-14 13:17 UTC, paulor3nato commented on requirements.txt
> +pydantic
el pydantic no puede subirse a la version 2

2024-11-18 13:58 UTC, paulor3nato approved these changes

2024-11-18 13:59 UTC, merged